name = "OWENSAero"
uuid = "ac8500f8-acb1-479a-8630-5dcb97b7c093"
authors = ["Kevin R. Moore <kevmoor@sandia.gov> and contributors"]
version = "1.0.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
FLOWMath = "6cb5d3fb-0fe8-4cc2-bd89-9fe0b19a99d3"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
OWENSOpenFASTWrappers = "1f4f357c-c864-4b71-8437-d48f9e1bb3e6"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
FLOWMath = "0.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
